version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    package_updates:
      - dependency-name: "postcss"
      - dependency-name: "autoprefixer"
